### ISSUE TITLE
Extension doesn't build on current Arch

### ISSUE THREAD

**Issue by paulie-g** [samhh/bukubrow-webext#160]
I'm trying to build from git latest, but get the following error:

```
make prepare
make[1]: Entering directory '/home/paul/sw/buku/update.bukubrow/bukubrow-webext'
mkdir -p .build release
make[1]: Leaving directory '/home/paul/sw/buku/update.bukubrow/bukubrow-webext'
yarn && yarn build
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > styled-components@5.2.3" has unmet peer dependency "react-is@>= 16.8.0".
warning " > styled-sanitize@1.1.3" has incorrect peer dependency "react@>= 0.14.0 < 17.0.0-0".
warning " > styled-sanitize@1.1.3" has incorrect peer dependency "styled-components@^3.0.0".
[4/4] Building fresh packages...
$ rm -rf ./dist/ && mkdir ./dist/ && cp ./src/assets/* ./dist/
Done in 4.63s.
yarn run v1.22.10
$ yarn run prepare && parcel build ./src/content.html ./src/options.html ./src/backend.ts
$ rm -rf ./dist/ && mkdir ./dist/ && cp ./src/assets/* ./dist/
⚠️  Could not load existing sourcemap of "../node_modules/react-highlight-words/dist/main.js".
🚨  /home/paul/sw/buku/update.bukubrow/bukubrow-webext/src/components/bookmark.tsx: Unexpected token: operator (?)
    at Z.get (/home/paul/sw/buku/update.bukubrow/bukubrow-webext/node_modules/terser/dist/bundle.min.js:1:525)
    at Object.errorToJson (/home/paul/sw/buku/update.bukubrow/bukubrow-webext/node_modules/@parcel/utils/src/errorUtils.js:9:20)
    at Pipeline.process (/home/paul/sw/buku/update.bukubrow/bukubrow-webext/node_modules/parcel-bundler/src/Pipeline.js:29:26)
    at async Object.run (/home/paul/sw/buku/update.bukubrow/bukubrow-webext/node_modules/parcel-bundler/src/worker.js:15:12)
    at async Child.handleRequest (/home/paul/sw/buku/update.bukubrow/bukubrow-webext/node_modules/@parcel/workers/src/child.js:60:26)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [makefile:37: webext] Error 1
```

**Comment by samhh** [comment]
Don't have the energy to investigate why this only started failing now but this should fix it: https://github.com/samhh/bukubrow-webext/commit/a063cf651bae0bd55022a90ded247571437b8374

**Comment by paulie-g** [comment]
FWIW, I've been using your extension for ages now, probably a year+. Just got around to upgrading since the initial setup and all of the remaining usability issues have been resolved with the current version. Sorry I didn't find the bug myself - looking at the commit, it seems obvious now even though I've no familiarity with TS. Thank you very much for the project.
